# Generated by Django 4.2.5 on 2023-09-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('picture', models.URLField(max_length=100)),
            ],
        ),
    ]
